repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.284
  hooks:
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/PyCQA/autoflake
  rev: v2.2.0
  hooks:
  - id: autoflake
- repo: https://github.com/crate-ci/typos
  rev: v1.16.21
  hooks:
  - id: typos
- repo: local
  hooks:
    - id: mypy
      name: mypy
      description: ''
      entry: mypy
      language: python
      'types_or': [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: '2.9.2'
      files: '^(?:src|tests)/'