name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    paths:
    - '.github/workflows/release.yml'

env:
  dists-artifact-name: python-package-distributions

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - run: python3 -m pip install build
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.dists-artifact-name }}
        path: dist/
  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/pytest-iovis
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.dists-artifact-name }}
        path: dist/
    - uses: pypa/gh-action-pypi-publish@release/v1
